---
rdma_host: node-03
host_fabrics:
  - ib0
  - opa0
  - iw
  - roce
hardware:
  - [00:07:43:5b:ec:a0, b8:ce:f6:09:66:fb]
gids:
  - [b8:ce:f6:03:00:09:66:fa, 00:11:75:09:01:c7:88:87]

clear_default_interfaces: true

interfaces:
  - dev: lom_1
    type: ethernet
    hwaddr: d4:f5:ef:0e:86:10
    dhcp: true
    defroute: true
  - dev: lom_2
    hwaddr: d4:f5:ef:0e:86:11
  - dev: lom_3
    hwaddr: d4:f5:ef:0e:86:12
  - dev: lom_4
    hwaddr: d4:f5:ef:0e:86:13
  - dev: cxgb4_off
    hwaddr: 00:07:43:5b:ec:a8

rdma_interfaces:
  - dev: mlx5
    fabric: ib0
    guid: 00:00:11:07:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:09:66:fa
    dhcp: true
  - dev: hfi1
    fabric: opa0
    guid: 80:81:00:02:fe:80:00:00:00:00:00:00:00:11:75:09:01:c7:88:87
    dhcp: true
  - dev: mlx5
    fabric: roce
    guid: b8:ce:f6:09:66:fb
    dhcp: true
  - dev: cxgb4
    fabric: iw
    guid: 00:07:43:5b:ec:a0
    dhcp: true

multicast_route: hfi1_opa0
setup_nfs_mounts: true
...
