---
rdma_host: node-09
host_fabrics:
  - ib0
  - ib0_1
  - iw
  - roce
  - roce_1
  - roce_2
hardware:
  - ["34:80:0d:b4:9c:96", "34:80:0d:b4:9c:97"]
  - ["b8:ce:f6:2c:5f:df"]
  - ["b8:ce:f6:2c:5f:e3"]

gids:
  - ["b8:ce:f6:03:00:2c:5f:de"]
  - ["b8:ce:f6:03:00:2c:5f:e2"]


clear_default_interfaces: true

interfaces:
  - dev: lom_1
    type: ethernet
    hwaddr: d4:f5:ef:0e:81:dc
    dhcp: true
    defroute: true
  - dev: lom_2
    hwaddr: d4:f5:ef:0e:81:dd
  - dev: lom_3
    hwaddr: d4:f5:ef:0e:81:de
  - dev: lom_4
    hwaddr: d4:f5:ef:0e:81:df

rdma_interfaces:
  - dev: mlx5
    fabric: ib0
    guid: 00:00:05:08:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:5f:de
    dhcp: true
  - dev: mlx5
    fabric: ib0_1
    guid: 00:00:09:a6:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:5f:e2
    dhcp: true
  - dev: qedr
    fabric: roce
    guid: 34:80:0d:b4:9c:96
    dhcp: true
  - dev: qedr
    fabric: iw
    guid: 34:80:0d:b4:9c:97
    dhcp: true
  - dev: mlx5
    fabric: roce_1
    guid: b8:ce:f6:2c:5f:df
    dhcp: true
  - dev: mlx5
    fabric: roce_2
    guid: b8:ce:f6:2c:5f:e3
    static_host: 47

multicast_route: mlx5_ib0
setup_nfs_mounts: true
...
