---
rdma_host: node-06
host_fabrics:
  - ib0
  - roce
  - roce_1
  - iw
hardware:
  - [b8:ce:f6:2d:15:cf, 00:07:43:4b:85:f0]
  - [00:0a:f7:31:49:60]
gids:
  - [b8:ce:f6:03:00:2d:15:ce]


clear_default_interfaces: true

interfaces:
  - dev: lom_1
    type: ethernet
    hwaddr: d4:f5:ef:0e:7e:f0
    dhcp: true
    defroute: true
  - dev: lom_2
    hwaddr: d4:f5:ef:0e:7e:f1
  - dev: lom_3
    hwaddr: d4:f5:ef:0e:7e:f2
  - dev: lom_4
    hwaddr: d4:f5:ef:0e:7e:f3
  - dev: bnxt_off
    hwaddr: 00:0a:f7:31:49:61
  - dev: cxgb4_off
    hwaddr: 00:07:43:4b:85:f8

rdma_interfaces:
  - dev: mlx5
    fabric: ib0
    guid: 00:00:05:4e:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2d:15:ce
    dhcp: true
  - dev: mlx5
    fabric: roce
    guid: b8:ce:f6:2d:15:cf
    dhcp: true
  - dev: bnxt
    fabric: roce_1
    guid: 00:0a:f7:31:49:60
    dhcp: true
  - dev: cxgb4
    fabric: iw
    guid: 00:07:43:4b:85:f0
    dhcp: true

multicast_route: bnxt0_roce_1
setup_nfs_mounts: true
...
