---
rdma_host: node-10
host_fabrics:
  - ib0
  - ib0_1
  - iw
  - roce
  - roce_1
  - roce_2
hardware:
  - [34:80:0d:b4:9f:1e, 34:80:0d:b4:9f:1f]
  - [b8:ce:f6:2c:5f:ff]
  - [b8:ce:f6:2c:60:03]
gids:
  - [b8:ce:f6:03:00:2c:5f:fe]
  - [b8:ce:f6:03:00:2c:60:02]

clear_default_interfaces: true

interfaces:
  - dev: lom_1
    type: ethernet
    hwaddr: d4:f5:ef:0e:8a:7c
    dhcp: true
    defroute: true
  - dev: lom_2
    hwaddr: d4:f5:ef:0e:8a:7d
  - dev: lom_3
    hwaddr: d4:f5:ef:0e:8a:7e
  - dev: lom_4
    hwaddr: d4:f5:ef:0e:8a:7f

rdma_interfaces:
  - dev: mlx5
    fabric: ib0
    guid: 00:00:06:7f:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:5f:fe
    dhcp: true
  - dev: mlx5
    fabric: ib0_1
    guid: 00:00:08:5f:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:60:02
    dhcp: true
  - dev: qedr
    fabric: roce
    guid: 34:80:0d:b4:9f:1e
    dhcp: true
  - dev: qedr
    fabric: iw
    guid: 34:80:0d:b4:9f:1f
    dhcp: true
  - dev: mlx5
    fabric: roce_1
    guid: b8:ce:f6:2c:5f:ff
    dhcp: true
  - dev: mlx5
    fabric: roce_2
    guid: b8:ce:f6:2c:60:03
    static_host: 52

multicast_route: mlx5_ib0
setup_nfs_mounts: true
...
