---
rdma_host: node-04
host_fabrics:
  - ib0
  - opa0
  - iw
  - roce
hardware:
  - [b8:ce:f6:09:66:db, 00:07:43:5b:ed:70]
gids:
  - [00:11:75:09:01:c7:8a:b0, b8:ce:f6:03:00:09:66:da]

clear_default_interfaces: true

interfaces:
  - dev: lom_1
    type: ethernet
    hwaddr: d4:f5:ef:0e:83:c0
    dhcp: true
    defroute: true
  - dev: lom_2
    hwaddr: d4:f5:ef:0e:83:c1
  - dev: lom_3
    hwaddr: d4:f5:ef:0e:83:c2
  - dev: lom_4
    hwaddr: d4:f5:ef:0e:83:c3
  - dev: cxgb4_off
    hwaddr: 00:07:43:5b:ed:78

rdma_interfaces:
  - dev: mlx5
    fabric: ib0
    guid: 00:00:02:b9:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:09:66:da
    dhcp: true
  - dev: hfi1
    fabric: opa0
    guid: 80:81:00:02:fe:80:00:00:00:00:00:00:00:11:75:09:01:c7:8a:b0
    dhcp: true
  - dev: mlx5
    fabric: roce
    guid: b8:ce:f6:09:66:db
    dhcp: true
  - dev: cxgb4
    fabric: iw
    guid: 00:07:43:5b:ed:70
    dhcp: true

multicast_route: hfi1_opa0
setup_nfs_mounts: true
...
