---
- name: Print distribution and arch information
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_architecture }}"

# - name: Import RPM key # Maybe unnecessary, actually fails on production
#   ansible.builtin.rpm_key:
#     state: present
#     key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture | lower }}"

# Loop task imports
- name: Import common tasks
  ansible.builtin.include_tasks:
    file: "{{ task_file }}.yml"
  loop_control:
    loop_var: task_file
  loop:
    - update_etc_hosts
    - unlimit_resources
    - install_packages
    - usability_enhancements
    - get_macs_of_host
    - fix_boot_loader
    - setup_ssh

- name: Reset security contexts
  ansible.builtin.command:
    cmd: "restorecon -R /root /etc /boot /lib"
...
