#!/bin/bash
RDMA_HOST=node-05
HOST_FABRICS=(roce iw)

Clear_Default_Interfaces

Create_Interface lom_1 Ethernet yes hwaddr d4:f5:ef:0e:7e:e4 dhcp defroute
Create_Interface lom_2 Ethernet no hwaddr d4:f5:ef:0e:7e:e5
Create_Interface lom_3 Ethernet no hwaddr d4:f5:ef:0e:7e:e6
Create_Interface lom_4 Ethernet no hwaddr d4:f5:ef:0e:7e:e7

Create_Rdma_Interfaces bnxt roce 00:0a:f7:31:49:50 dhcp
Create_Interface bnxt_off Ethernet no hwaddr 00:0a:f7:31:49:51
Create_Rdma_Interfaces cxgb4 iw 00:07:43:4b:86:e0 dhcp
Create_Interface cxgb4_off Ethernet no hwaddr 00:07:43:4b:86:e8

Create_Multicast_Route bnxt0_roce

Create_Fixed_Addresses ${HOST_FABRICS[*]}
HARDWARE0=(00:0a:f7:31:49:50 00:07:43:4b:86:e0)
#GIDS0=(b8:ce:f6:03:00:2c:5f:de b8:ce:f6:03:00:2c:5f:e2)

Setup_Nfs_Client_Mounts
