#!/bin/bash
RDMA_HOST=node-09
HOST_FABRICS=(ib0 roce)

Clear_Default_Interfaces

Create_Interface lom_1 Ethernet yes hwaddr d4:f5:ef:0e:81:dc dhcp defroute
Create_Interface lom_2 Ethernet no hwaddr d4:f5:ef:0e:81:dd
Create_Interface lom_3 Ethernet no hwaddr d4:f5:ef:0e:81:de
Create_Interface lom_4 Ethernet no hwaddr d4:f5:ef:0e:81:df

Create_Rdma_Interfaces mlx5 ib0 00:00:03:06:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:09:66:da dhcp
Create_Interface mlx5_off ipoib no hwaddr 00:00:03:06:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:09:66:db
Create_Rdma_Interfaces qedr0 roce 34:80:0d:b4:9c:96 dhcp
Create_Interface qedr1_off Ethernet no hwaddr 34:80:0d:b4:9c:97

Create_Multicast_Route mlx5_ib0

Create_Fixed_Addresses ${HOST_FABRICS[*]}
HARDWARE=(34:80:0d:b4:9c:96)
GIDS=(b8:ce:f6:03:00:09:66:da)

Setup_Nfs_Client_Mounts
