#!/bin/bash
RDMA_HOST=node-10
HOST_FABRICS=(ib0 ib0_1 iw roce roce_1 roce_2)

Clear_Default_Interfaces

Create_Interface lom_1 Ethernet yes hwaddr d4:f5:ef:0e:8a:7c dhcp defroute
Create_Interface lom_2 Ethernet no hwaddr d4:f5:ef:0e:8a:7d
Create_Interface lom_3 Ethernet no hwaddr d4:f5:ef:0e:8a:7e
Create_Interface lom_4 Ethernet no hwaddr d4:f5:ef:0e:8a:7f

Create_Rdma_Interfaces mlx5 ib0 00:00:06:7f:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:5f:fe dhcp
Create_Rdma_Interfaces mlx5 ib0_1 00:00:08:5f:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:2c:60:02 dhcp
Create_Rdma_Interfaces qedr roce 4:80:0d:b4:9f:1e dhcp
Create_Rdma_Interfaces qedr iw 34:80:0d:b4:9f:1f dhcp
Create_Rdma_Interfaces mlx5 roce_1 b8:ce:f6:2c:5f:ff dhcp
Create_Rdma_Interfaces mlx5 roce_2 b8:ce:f6:2c:60:03 47

Create_Multicast_Route mlx5_ib0

Create_Fixed_Addresses ${HOST_FABRICS[*]}
HARDWARE0=(4:80:0d:b4:9f:1e 34:80:0d:b4:9f:1f)
HARDWARE1=(b8:ce:f6:2c:5f:ff)
HARDWARE2=(b8:ce:f6:2c:60:03)
GIDS0=(b8:ce:f6:03:00:2c:5f:fe)
GIDS1=(b8:ce:f6:03:00:2c:60:02)

Setup_Nfs_Client_Mounts
