#!/bin/bash
RDMA_HOST=node-08
HOST_FABRICS=(roce roce_1)

Clear_Default_Interfaces

Create_Interface lom_1 Ethernet yes hwaddr 48:df:37:ca:fb:60 dhcp defroute
Create_Interface lom_2 Ethernet no hwaddr 48:df:37:ca:fb:61
Create_Interface lom_3 Ethernet no hwaddr 48:df:37:ca:fb:62
Create_Interface lom_4 Ethernet no hwaddr 48:df:37:ca:fb:63

Create_Rdma_Interfaces mlx5 roce b8:ce:f6:44:ea:dc dhcp
Create_Rdma_Interfaces bnxt roce_1 bc:97:e1:70:3d:20 dhcp
Create_Interface bnxt_off Ethernet no hwaddr bc:97:e1:70:3d:21

Create_Multicast_Route mlx5_roce

Create_Fixed_Addresses ${HOST_FABRICS[*]}
HARDWARE0=(b8:ce:f6:44:ea:dc)
HARDWARE1=(bc:97:e1:70:3d:20)

Setup_Nfs_Client_Mounts
