#!/bin/bash
RDMA_HOST=node-03
HOST_FABRICS=(ib0 opa0 iw roce)

Clear_Default_Interfaces

Create_Interface lom_1 Ethernet yes hwaddr d4:f5:ef:0e:86:10 dhcp defroute
Create_Interface lom_2 Ethernet no hwaddr d4:f5:ef:0e:86:11
Create_Interface lom_3 Ethernet no hwaddr d4:f5:ef:0e:86:12
Create_Interface lom_4 Ethernet no hwaddr d4:f5:ef:0e:86:13

Create_Rdma_Interfaces mlx5 ib0 00:00:11:07:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:09:66:fa dhcp
Create_Rdma_Interfaces hfi1 opa0 80:81:00:02:fe:80:00:00:00:00:00:00:00:11:75:09:01:c7:88:87 dhcp
Create_Rdma_Interfaces mlx5 roce b8:ce:f6:09:66:fb dhcp
Create_Rdma_Interfaces cxgb4 iw 00:07:43:5b:ec:a0 dhcp
Create_Interface cxgb4_off Ethernet no hwaddr 00:07:43:5b:ec:a8

Create_Multicast_Route hfi1_opa0

Create_Fixed_Addresses ${HOST_FABRICS[*]}
HARDWARE=(00:07:43:5b:ec:a0 b8:ce:f6:09:66:fb)
GIDS=(b8:ce:f6:03:00:09:66:fa 00:11:75:09:01:c7:88:87)

Setup_Nfs_Client_Mounts
