#!/bin/bash

SRP_SERVERS=(rdma-storage-01 rdma-storage-02 rdma-storage-03 rdma-storage-04)
ISER_SERVERS=(rdma-storage-01 rdma-storage-02 rdma-storage-03 rdma-storage-04)
NVME_SERVERS=(rdma-storage-02 rdma-storage-04)

# iSER target name format is $ISER_PREFIX:$server
iqn="iqn.1994-05.com.redhat"

#iSER portal access IP will be $fabric-$server_part
declare -A ISER_FABRICS
ISER_FABRICS[rdma-storage-01]="ib0 ib1 roce iw"
ISER_FABRICS[rdma-storage-02]="ib0 ib1 roce iw"
ISER_FABRICS[rdma-storage-03]="ib0 ib1 roce"
ISER_FABRICS[rdma-storage-04]="ib0 ib1 roce"

declare -A SRP_FABRICS
SRP_FABRICS[rdma-storage-01]="ib0 ib1"
SRP_FABRICS[rdma-storage-02]="ib0 ib1"
SRP_FABRICS[rdma-storage-03]="ib0 ib1"
SRP_FABRICS[rdma-storage-04]="ib0 ib1"

declare -A SRP_DGID
SRP_DGID[rdma-storage-01-ib0]="fe80000000000000f4521403007bcba1"
SRP_DGID[rdma-storage-01-ib1]="fe80000000000001001175000078b784"
SRP_DGID[rdma-storage-02-ib0]="fe8000000000000000117500006f3370"
SRP_DGID[rdma-storage-02-ib1]="fe8000000000000100117500006f3371"
SRP_DGID[rdma-storage-03-ib0]="fe80000000000000e41d2d03001d6471"
SRP_DGID[rdma-storage-03-ib1]="fe80000000000001e41d2d03001d6491"
SRP_DGID[rdma-storage-04-ib0]="fe80000000000000e41d2d0300e70e7e"
SRP_DGID[rdma-storage-04-ib1]="fe80000000000001e41d2d0300e70e7f"

