#!/bin/bash

SRP_SERVERS=(builder-00)
ISER_SERVERS=(builder-00)
NVME_SERVERS=(builder-00)

# iSER target name format is $ISER_PREFIX:$server
iqn="iqn.1994-05.edu.unh.iol.ofa"

#iSER portal access IP will be $fabric-$server_part
declare -A ISER_FABRICS
ISER_FABRICS[builder-00]="ib0 opa0 roce"

declare -A SRP_FABRICS
SRP_FABRICS[builder-00]="ib0"

declare -A SRP_DGID
SRP_DGID[builder-00-ib0]="fe80000000000000f4521403007bcba1"

